version: '3.3'

services:
  
  db:
    image: signup-db
    networks:
      - app-net

  message-queue:
    image: nats:nanoserver
    networks:
      - app-net

  web:
    image: signup-web
    depends_on:
      - db
      - message-queue
    networks:
      - app-net

  save-handler:
    image: signup-save-handler
    depends_on:
      - db
      - message-queue
    networks:
      - app-net

  index-handler:
    image: signup-index-handler
    depends_on:
      - elasticsearch
      - message-queue
    networks:
      - app-net

  elasticsearch:
    image: elasticsearch:5.2.0-nanoserver
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    networks:
      - app-net

  kibana:
    image: kibana:5.2.0-windowsservercore-10.0.14393.1715
    depends_on:
      - elasticsearch
    networks:
      - app-net

networks:
  app-net: