version: '3.2'
services:
  web:
    image: microsoft/windowsservercore:10.0.14393.1715
    deploy:
      placement:
        constraints:
          - node.platform.os == windows
    command: ping bing.com -t
